# Gitleaks configuration for detecting secrets
title = "Transcriber Gitleaks Config"

[allowlist]
description = "Allowlist for transcriber project"
paths = [
  '''.env.example''',
  '''*.test.ts''',
  '''*.test.js''',
]

# Allow mock/test API keys in tests
regexes = [
  '''test-api-key''',
  '''your-.*-api-key-here''',
  '''mock[A-Za-z]*Key''',
]

[[rules]]
description = "Gemini API Key"
regex = '''(?i)(gemini[_\-]?api[_\-]?key|google[_\-]?api[_\-]?key)['"]?\s*[:=]\s*['"]?[A-Za-z0-9\-_]{39}'''
tags = ["key", "gemini", "google"]

[[rules]]
description = "OpenAI API Key"
regex = '''(?i)(openai[_\-]?api[_\-]?key)['"]?\s*[:=]\s*['"]?sk-[A-Za-z0-9]{48}'''
tags = ["key", "openai"]

[[rules]]
description = "Generic API Key"
regex = '''(?i)(api[_\-]?key|apikey)['"]?\s*[:=]\s*['"]?[A-Za-z0-9\-_]{20,}'''
tags = ["key", "generic"]

[[rules]]
description = "Generic Secret"
regex = '''(?i)(secret|password|passwd|pwd|token|auth)['"]?\s*[:=]\s*['"]?[A-Za-z0-9\-_!@#$%^&*]{8,}'''
tags = ["secret", "generic"]